# Default initial positions for gen3_lite_gen3_lite_2f's ros2_control fake system

initial_positions:
  joint_1: 0
  joint_2: 0
  joint_3: 0
  joint_4: 0
  joint_5: 0
  joint_6: 0
  right_finger_bottom_joint: 0
