moveit_simple_controller_manager:
  controller_names:
    - gen3_lite_joint_trajectory_controller
    - gen3_lite_2f_gripper_controller

  gen3_lite_joint_trajectory_controller:
    type: FollowJointTrajectory
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
    action_ns: follow_joint_trajectory
    default: true
  gen3_lite_2f_gripper_controller:
    type: GripperCommand
    joints:
      - right_finger_bottom_joint
    action_ns: gripper_cmd
    default: true
