name: ROS2 Lint
on:
  pull_request:

jobs:
  ament_lint:
    name: ament_${{ matrix.linter }}
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
          linter: [cppcheck, copyright]
    steps:
    - uses: actions/checkout@v3
    - uses: ros-tooling/setup-ros@v0.6
    - uses: ros-tooling/action-ros-lint@v0.1
      with:
        distribution: rolling
        linter: ${{ matrix.linter }}
        package-name:
          kortex_bringup
          kortex_driver

  # ament_lint_cmake complains about [readability/wonkycase]
  # but there is no argument to ignore the wonky case
  # the pre-commit hook also skips kortex_driver and kortex_api
  ament_lint_cmake:
    name: ament_lint_cmake
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
    - uses: ros-tooling/setup-ros@v0.6
    - uses: ros-tooling/action-ros-lint@v0.1
      with:
        distribution: rolling
        linter: lint_cmake
        package-name:
          kortex_bringup

  ament_lint_100:
    name: ament_${{ matrix.linter }}
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
          linter: [cpplint]
    steps:
    - uses: actions/checkout@v3
    - uses: ros-tooling/setup-ros@v0.6
    - uses: ros-tooling/action-ros-lint@v0.1
      with:
        distribution: rolling
        linter: cpplint
        arguments: "--linelength=100 --filter=-whitespace/newline --exclude=kortex_driver/src/kortex_math_util.cpp"
        package-name:
          kortex_bringup
          kortex_driver
